import type { Metadata } from "next";
import {
  SeoLandingPage,
  type SeoFaq,
} from "../components/SeoLandingPage";

const title = "AI App Builder with Editable Code";
const description =
  "Build browser-based apps with AI, inspect every generated file, test changes in a restricted live preview, and export code you can keep.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/ai-app-builder" },
  openGraph: {
    title: `${title} | SkyCode`,
    description,
    url: "/ai-app-builder",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `${title} | SkyCode`,
    description,
  },
};

const faqs: SeoFaq[] = [
  {
    question: "What is an AI app builder?",
    answer:
      "An AI app builder converts a plain-language product request into a working software draft. SkyCode keeps the generated HTML, CSS, JavaScript, and project files visible so you can review and edit the result.",
  },
  {
    question: "Do I need coding experience to start?",
    answer:
      "No. You can begin by describing the product, audience, pages, and actions you need. Coding knowledge becomes useful when you want deeper control, but it is not required to create the first browser project.",
  },
  {
    question: "Can I edit the code generated by AI?",
    answer:
      "Yes. SkyCode is designed around an editable file tree and code editor. AI suggestions remain reviewable, and you can change the files directly before running or exporting the project.",
  },
  {
    question: "What can the current SkyCode workspace build?",
    answer:
      "The current public workspace is focused on HTML, CSS, JavaScript, and JSON browser projects with restricted live preview. Broader package installation and multi-language execution require the isolated runtime described in the security documentation.",
  },
];

export default function AiAppBuilderPage() {
  return (
    <SeoLandingPage
      path="/ai-app-builder"
      eyebrow="AI APP BUILDER"
      title={title}
      description={description}
      proof={["Prompt-to-code workflow", "Full file visibility", "Restricted live preview", "Exportable source"]}
      sectionTitle="AI speed without giving up technical control."
      sectionDescription="Many app generators hide the implementation behind a visual layer. SkyCode keeps the working files, preview, project history, and AI conversation together so the result stays understandable."
      benefits={[
        {
          title: "Turn product intent into a working draft",
          description:
            "Describe the user, business goal, pages, and interactions. Sky AI organizes the request into practical code changes instead of returning a disconnected snippet.",
        },
        {
          title: "Inspect and edit every generated file",
          description:
            "Open the file explorer, search across the project, review local changes, and edit the source directly. The AI remains an assistant, not a locked publishing layer.",
        },
        {
          title: "Preview browser output safely",
          description:
            "Run the project in a restricted preview surface that separates generated output from the editor and blocks unnecessary network, form, and framing capabilities.",
        },
        {
          title: "Keep a portable result",
          description:
            "Export a static HTML build and retain ordinary source files. Your first prototype stays useful even if you later move it into a larger development workflow.",
        },
      ]}
      steps={[
        {
          title: "Describe the outcome",
          description:
            "State who the app is for, the problem it solves, and the most important action a user should complete.",
        },
        {
          title: "Review the generated structure",
          description:
            "Inspect the files and preview before accepting visual or functional decisions.",
        },
        {
          title: "Refine with prompts or direct edits",
          description:
            "Ask for focused changes, search the codebase, or edit a file yourself when precision matters.",
        },
        {
          title: "Save, test, and export",
          description:
            "Create a project checkpoint, rerun the preview, and export the source when the result is ready.",
        },
      ]}
      useCases={[
        {
          title: "Startup MVPs",
          description:
            "Prototype the core user journey for a SaaS dashboard, customer portal, internal workflow, or simple marketplace interface.",
        },
        {
          title: "Business tools",
          description:
            "Create focused calculators, trackers, forms, reporting views, and operational dashboards for a team.",
        },
        {
          title: "Interactive prototypes",
          description:
            "Turn a product idea into something stakeholders can click, review, and improve before full engineering begins.",
        },
        {
          title: "Learning projects",
          description:
            "Study how HTML, CSS, and JavaScript work together while comparing an AI suggestion with the actual generated source.",
        },
      ]}
      faqs={faqs}
    />
  );
}
